@baseUrl = http://localhost:3000

# create_task
POST {{baseUrl}}/task
Content-Type: application/json

{
  "title": "titulo marcio",
  "description": "descrição marcio"
}

###

# fetch_tasks
GET {{baseUrl}}/task

###

# update_task
PUT {{baseUrl}}/task/1f55a1b7-e854-430f-8101-0ea3c8953922
Content-Type: application/json

{
  "title": "titulo novo",
  "description": "descrição"
}

###

# delete_task
DELETE {{baseUrl}}/task/0f1a2c11-0d8b-4b43-8e5c-c1cc8376c789
Content-Type: application/json

{
  "title": "titulo novo",
  "description": "descrição"
}

###

# complete_task
PATCH {{baseUrl}}/task/3fe18c35-d5d6-4b2f-894b-ec56376c586b/complete